name: Documentation PRs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out the code
      - name: Lint Code Base
        uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
        with:
          args: "--disable MD009 -- docs/**/*.md"
  spellcheck:
    name: "Spell check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out the code
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 18
      - run: npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./docs/cSpell.json "docs/**/*.md"
        name: run cSpell

      - name: Build docs
        run: ./build.sh --no-color docs-import-v3
